import type { Lead } from './types';

export const initialLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Ana Silva',
    role: 'Gerente de Compras',
    company: 'Construtora Segura',
    cnpj: '12.345.678/0001-99',
    proposalSummary: 'Consultoria completa em segurança do trabalho para nova obra.',
    value: 15000,
    paymentMethods: [{ method: 'Boleto' }, { method: 'Cartão de Crédito (Link)', cardFee: 3.5 }],
    contactSource: { source: 'Google' },
    email: 'ana.silva@construtorasegura.com.br',
    whatsapp: '11987654321',
    status: 'Novos',
    rejectionReason: null,
    createdAt: new Date(),
  },
  {
    id: 'lead-2',
    name: 'Bruno Costa',
    role: 'Diretor Industrial',
    company: 'Indústria Têxtil Faria',
    cnpj: '98.765.432/0001-11',
    proposalSummary: 'Treinamento de NR-12 para equipe de produção.',
    value: 22000,
    paymentMethods: [{ method: 'Boleto' }],
    contactSource: { source: 'Indicação', indicatedBy: 'Carlos Mendes' },
    email: 'bruno.costa@faria.ind.br',
    whatsapp: '21998765432',
    status: 'Novos',
    rejectionReason: null,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)),
  },
  {
    id: 'lead-3',
    name: 'Carla Dias',
    role: 'Coordenadora de RH',
    company: 'Metalúrgica Diniz',
    cnpj: '45.678.912/0001-33',
    proposalSummary: 'Laudo de periculosidade e insalubridade.',
    value: 8500,
    paymentMethods: [{ method: 'Cartão de Crédito (Maquininha)', cardFee: 4.0 }],
    contactSource: { source: 'BNI' },
    email: 'carla.dias@metalurgicadiniz.com',
    whatsapp: '31987651234',
    status: 'Pendente/Em negociação',
    rejectionReason: null,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
  },
  {
    id: 'lead-4',
    name: 'Daniel Martins',
    role: 'Diretor Administrativo',
    company: 'Hospital Vida Plena',
    cnpj: '78.912.345/0001-55',
    proposalSummary: 'Implementação de CIPA e elaboração de mapa de riscos.',
    value: 35000,
    paymentMethods: [{ method: 'Boleto' }],
    contactSource: { source: 'Instagram' },
    email: 'daniel.martins@vidaplena.com',
    whatsapp: '41998762345',
    status: 'Aprovado',
    rejectionReason: null,
    createdAt: new Date(new Date().setMonth(new Date().getMonth() - 2)),
  },
  {
    id: 'lead-5',
    name: 'Eduarda Ferreira',
    role: 'Diretora Pedagógica',
    company: 'Escola Aprender Mais',
    cnpj: '15.935.782/0001-77',
    proposalSummary: 'AVCB e treinamento de brigada de incêndio.',
    value: 12000,
    paymentMethods: [{ method: 'Boleto' }, { method: 'Cartão de Crédito (Link)', cardFee: 3.8 }],
    contactSource: { source: 'Marketing Offline' },
    email: 'eduarda.ferreira@aprendermais.com',
    whatsapp: '51987653456',
    status: 'Desistência',
    rejectionReason: 'Concorrência com melhor oferta',
    createdAt: new Date(new Date().setMonth(new Date().getMonth() - 3)),
  },
  {
    id: 'lead-6',
    name: 'Fábio Gomes',
    role: 'Gerente de Operações',
    company: 'Supermercado Central',
    cnpj: '82.468.135/0001-99',
    proposalSummary: 'PGR e PCMSO para todas as unidades.',
    value: 18000,
    paymentMethods: [{ method: 'Boleto' }],
    contactSource: { source: 'Google' },
    email: 'fabio.gomes@supercentral.com',
    whatsapp: '61998764567',
    status: 'Rejeitado',
    rejectionReason: 'Preço elevado',
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
  },
  {
    id: 'lead-7',
    name: 'Gabriela Lima',
    role: 'CTO',
    company: 'Tecnologia Inova',
    cnpj: '36.925.814/0001-21',
    proposalSummary: 'Análise Ergonômica do Trabalho (AET) para o setor de desenvolvimento.',
    value: 25000,
    paymentMethods: [{ method: 'Cartão de Crédito (Link)', cardFee: 3.2 }],
    contactSource: { source: 'Indicação', indicatedBy: 'Juliana Paes' },
    email: 'gabriela.lima@tecinova.com.br',
    whatsapp: '71987655678',
    status: 'Rejeitado',
    rejectionReason: 'Cliente optou por solução interna',
    createdAt: new Date(),
  },
];
